name: Compressor
version: 0.1.1
author: InspectorElement
main: dev.solidsilver.compressor.Main
api-version: 1.16
commands:
  compressedCobble:
    description: Gives the player a block of compressed cobble of the specified level
    usage: /<command> <level>
    aliases: [cc]