name: ItemsPlus
version: 0.1.3
author: InspectorElement
main: dev.solidsilver.testplugin.Main
api-version: 1.16
commands:
  compressedCobble:
    description: Gives the player a block of compressed cobble of the specified level
    usage: /<command> <level>
    aliases: [cc]
